BEGIN;

CREATE ROLE admin LOGIN SUPERUSER;
CREATE ROLE teacher LOGIN NOSUPERUSER;
CREATE ROLE student LOGIN NOSUPERUSER;

REVOKE USAGE ON SCHEMA public FROM admin, teacher, student;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM admin, teacher, student;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM admin, teacher, student;

GRANT USAGE, CREATE ON SCHEMA public TO admin;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO admin;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO admin;

GRANT USAGE ON SCHEMA public TO student;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO student;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO student;

GRANT student TO teacher;

GRANT SELECT, INSERT, UPDATE, DELETE ON "Mark" TO teacher;
GRANT SELECT, INSERT, UPDATE, DELETE ON "Work" TO teacher;

COMMIT;
